;=========================================================
; SNIPER Utilities Suite
; Version : 2.0 Build 1001
;=========================================================

[General]
Version=2.0.1001
Company=SNIPER Utilities Suite
Author=Eng. Hafeez Ur Rehman

[Computers]
Primary=SNIPER-HP
Secondary=SNIPER-MBP

[Network]
HPShare=\\SNIPER-HP\Hafeez
MBPShare=\\SNIPER-MBP\Hafeez

[Folders]
HPData=D:\Hafeez
MBPData=C:\Hafeez

Logs=Logs

[Credentials]
User=netshare