;=========================================================
; SNIPER Utilities Suite
; Version 1.0.0-alpha2
; Author: Eng. Hafeez Ur Rehman
;=========================================================

[General]
SuiteName=SNIPER Utilities Suite
Version=1.0.0-alpha2

[Backup]
Source=D:\Hafeez\Final Resumes
Destination=\\SNIPER-MBP\Hafeez
LogFolder=Logs
LogFile=Backup.log
RoboCopyOptions=/MIR /FFT /R:2 /W:2 /XJ /MT:8

[Network]
PrimaryComputer=SNIPER-HP
SecondaryComputer=SNIPER-MBP